language: minimal

matrix:
  include:
  - os: linux
    arch: arm64
    dist: focal
    services:
    - docker
  - os: osx

git:
  depth: 1

notifications:
  email: false

script:
- cd $TRAVIS_BUILD_DIR
- sh ./ci.sh
